site:
  name: ClashWiki
  site: 'https://clashwiki.cc'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: ClashWiki - Clash 客户端下载与网络代理配置教程 Wiki
    template: '%s — ClashWiki'
  description: "ClashWiki 专注于提供最新 Clash 客户端官方下载指引、规则分流配置、网络代理软件教程及机场评测推荐，帮助您安全、高速、顺畅地连接全球互联网。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: ClashWiki
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

i18n:
  language: zh-CN
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
